name: Atualizar Versão de Cada Layout

on:
  workflow_run:
    workflows: ["Criar Tag e Release"]  # Espera a execução do workflow "Criar Tag e Release"
    types: [success]  # Executa quando o workflow "Criar Tag e Release" for completado (independentemente de sucesso ou falha)

  pull_request:
    types: [closed]  # Evento disparado quando o PR é fechado
    branches: 
      - main
      - develop  # Filtra as branches de destino (main ou develop)
permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório
  
jobs:
  executa-script-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify your desired Python version
      - name: Install gitpython
        run: |
          pip install gitpython

      - name: Debug GitHub context
        run: |
          echo "GitHub Token: ${{ secrets.GH_TOKEN }}"
          echo "Pull Request Head Ref: ${{ github.event.pull_request.head.ref }}"
          echo "Base Ref (branch de destino): ${{ github.base_ref }}"          
      - name: Run script atualizar-versao-cada-layout
        #run: python scripts/atualizar-versao-cada-layout.py ${{ secrets.GH_TOKEN }} ${{ github.head_ref }} ${{ github.base_ref }}
        run: python scripts/atualizar-versao-cada-layout.py ${{ secrets.GH_TOKEN }} ${{ github.event.pull_request.head.ref }} ${{ github.base_ref }}
