name: Atualizar Versão de Cada Layout

on:
  workflow_run:
    workflows: ["Criar Tag e Release"]
    types: [completed, success]
  pull_request:
    #types: [opened, synchronize, reopened]
    types: [closed]
    branches: [main, develop]   

permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório
  
jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify your desired Python version
      - name: Install gitpython
        run: |
          pip install gitpython
      - name: Run your script
        run: python scripts/atualizar-versao-cada-layout.py ${{ secrets.GH_TOKEN }} ${{ github.head_ref }} ${{ github.base_ref }}
