name: Capturar e Usar o Nome da Branch de Origem do PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'
permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório 
  
jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Passo 2: Gerar dados e salvar em arquivo
      - name: Gerar dados e salvar em arquivo
        run: |
          echo "${{ github.head_ref }}" > .github/branch-name.txt

      # Passo 3: Garantir que estamos na branch certa para fazer push
      - name: Checkout da branch main
        run: |
          git fetch origin main
          git checkout main

      # Passo 4: Commit e push do arquivo
      - name: Commit e push do arquivo
        run: |
          # Configurações de Git para commit e push
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Adicionar as mudanças ao git
          git add .github/branch-name.txt
          git commit -m "Salvar nome da branch no arquivo"
          
          # Autenticação com o token do GitHub
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
