name: Capturar e Usar o Nome da Branch de Origem do PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório
  
jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Salvar nome da branch na raiz
        run: |
          echo "${{ github.head_ref }}" > "/branch-name.txt"

      # Passo 4: Commit e push do arquivo, se houver alterações
      - name: Commit e push do arquivo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Verifica se houve alterações no arquivo antes de tentar o commit
          if [[ $(git diff --exit-code branch-name.txt) != "" ]]; then
            git add branch-name.txt
            git commit -m "Salvar nome da branch no arquivo"
            git push origin main
          else
            echo "Nenhuma alteração no arquivo branch-name.txt, nada para commit."
          fi

      - name: Verificar se o arquivo já existe
        run: |
          if [ ! -f "$GITHUB_WORKSPACE/branch-name.txt" ]; then
            echo "O arquivo branch-name.txt é necessário para continuar. Abortando."
            exit 1
          fi
