name: Capturar e Usar o Nome da Branch de Origem do PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'

jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Passo 2: Capturar o nome da branch de origem do PR e salvar em uma variável de ambiente
      - name: Capturar nome da branch de origem do PR
        id: capture-branch
        run: |
          # Captura o nome da branch de origem do PR
          PR_BRANCH="${{ github.head_ref }}"
          echo "Branch de origem do PR: $PR_BRANCH"
          
          # Salva o nome da branch em um arquivo temporário
          echo "$PR_BRANCH" > branch-name.txt

      - name: Upload branch name as artifact
        uses: actions/upload-artifact@v3
        with:
          name: branch-name
          path: branch-name.txt
