name: Capturar e Usar o Nome da Branch de Origem do PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'

jobs:
  capture-branch:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use o token correto aqui
    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Gerar dados e salvar em arquivo
        run: |
          # Crie o arquivo com os dados que você quer compartilhar
          echo "${{ github.head_ref }}" > .github/branch-name.txt

      - name: Commit e push do arquivo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .github/branch-name.txt
          git commit -m "Salvar nome da branch no arquivo"
          git push origin main

          # Adicionar as mudanças ao git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          # Autenticação com o token GH_TOKEN
          git config --global credential.helper 'cache --timeout=3600'
          echo "https://${{ secrets.GH_TOKEN }}:@github.com" > ~/.git-credentials
          
