name: Capturar e Usar o Nome da Branch de Origem do PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório
  
jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Specify your desired Python version
      - name: Install gitpython
        run: |
          pip install gitpython
      - name: Run your script
        run: python scripts/capturar-branch-origem.py --branch-name ${{ github.head_ref }}
