name: Capturar e Usar o Nome da Branch de Origem do PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório
  
jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Python script
        run: python scripts/capturar-branch-origem.py
