name: Capturar nome da branch de origem do PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'

jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Passo 1: Capturar o nome da branch de origem do PR
      - name: Capturar nome da branch de origem do PR
        id: get-pr-branch
        run: |
          # O nome da branch de origem do PR está em github.head_ref
          PR_BRANCH="${{ github.head_ref }}"
          echo "Branch de origem do PR: $PR_BRANCH"
          
          # Definir a variável de ambiente 'NAME_BRANCH_ORIGIN' para o nome da branch
          echo "NAME_BRANCH_ORIGIN=$PR_BRANCH" >> $GITHUB_ENV

      # Passo 2: Verificar se a variável foi definida corretamente
      - name: Verificar valor da variável de ambiente
        run: |
          echo "O valor da variável NAME_BRANCH_ORIGIN é: $NAME_BRANCH_ORIGIN"
         
