name: Capturar branch de origem do PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'

permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório

jobs:
  update-version:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use o token correto aqui
    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Passo 2: Capturar o nome da branch de origem do PR
      - name: Capturar nome da branch de origem do PR
        id: get-pr-branch
        run: |
          # O nome da branch de origem do PR está em github.head_ref
          PR_BRANCH="${{ github.head_ref }}"
          echo "Branch de origem do PR: $PR_BRANCH"
          
          # Salvar o nome da branch em um arquivo dentro da pasta .github/
          echo $PR_BRANCH > .github/branch-name.txt

      # Passo 3: Commitar e fazer o push do arquivo atualizado
      - name: Commit e push do arquivo com o nome da branch
        run: |
          # Configurar o Git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

          # Adicionar o arquivo alterado
          git add .github/branch-name.txt

          # Commitar as mudanças
          git commit -m "Salvar o nome da branch de origem do PR em .github/branch-name.txt"

          # Fazer push das mudanças
          git push origin HEAD:main

          # Autenticação com o token GH_TOKEN
          git config --global credential.helper 'cache --timeout=3600'
          echo "https://${{ secrets.GH_TOKEN }}:@github.com" > ~/.git-credentials
          
