name: Capturar e Usar o Nome da Branch de Origem do PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Salvar nome da branch na raiz
        run: |
          echo "${{ github.head_ref }}" > "$GITHUB_WORKSPACE/branch-name.txt"

      - name: Commitar alterações (se houver)
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.event.pull_request.head.user.email }}

          if [[ -n "$(git status --porcelain)" ]]; then
            git add branch-name.txt
            git commit -m "Salvar nome da branch: ${{ github.head_ref }} (PR #${{ github.event.number }})"
            git push origin main
          fi
