name: Capturar e Usar o Nome da Branch de Origem do PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'main'

jobs:
  capture-branch:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer o checkout do repositório
      - name: Check out repository
        uses: actions/checkout@v3

      # Passo 2: Gerar dados e salvar em arquivo
      - name: Gerar dados e salvar em arquivo
        run: |
          # Crie o arquivo com os dados que você quer compartilhar
          echo "${{ github.head_ref }}" > branch-name.txt

      # Passo 3: Verificar se o arquivo foi alterado
      - name: Verificar alterações no arquivo
        run: |
          # Verifica se houve alguma alteração no arquivo branch-name.txt
          git diff --exit-code branch-name.txt || echo "Alterações detectadas no arquivo branch-name.txt"

      # Passo 4: Commit e push do arquivo, se houver alterações
      - name: Commit e push do arquivo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Verifica se houve alterações no arquivo antes de tentar o commit
          if [[ $(git diff --exit-code branch-name.txt) != "" ]]; then
            git add branch-name.txt
            git commit -m "Salvar nome da branch no arquivo"
            git push origin main
          else
            echo "Nenhuma alteração no arquivo branch-name.txt, nada para commit."
          fi
