name: CI/CD - Criar Tag de Release

on:
  pull_request:
    types:
      - closed  # Aciona o workflow quando o PR for fechado
    branches:
      - main
      - develop  # Para monitorar as duas branches principais do repositório

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar usuário Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"      

    - name: Verificar se o PR foi mesclado
      run: |
        if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
          echo "PR foi mesclado!"
        else
          echo "PR não foi mesclado. Abortando o processo."
          exit 1
        fi

    - name: Determinar a branch de destino e criar a tag
      run: |
        BRANCH_NAME=${{ github.event.pull_request.base.ref }}
        TAG_NAME="v$(date +'%Y.%m.%d')-release"  # Exemplo de tag, use seu próprio formato

        echo "Criando tag para a branch: $BRANCH_NAME"

        if [[ "$BRANCH_NAME" == "main" ]]; then
          git tag -a "$TAG_NAME" -m "Release para main"
        elif [[ "$BRANCH_NAME" == "develop" ]]; then
          git tag -a "$TAG_NAME" -m "Release para develop"
        else
          echo "Branch não suportada para criação de tag. Abortando."
          exit 1
        fi

        # Enviar a tag para o repositório
        git push origin "$TAG_NAME"

    - name: Confirmar a tag criada
      run: |
        git tag -l  # Listar as tags para confirmar que a tag foi criada
