name: CI/CD - Criar Tag de Release
on:
  pull_request:
    types:
      - closed  # Aciona o workflow quando o PR for fechado
    branches:
      - main
      - develop  # Para monitorar as duas branches principais do repositório

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          use_github_release_notes: true
