name: CI/CD - Criar Tag de Release

on:
  pull_request:
    types:
      - closed  # Aciona o workflow quando o PR for fechado
    branches:
      - main
      - develop  # Para monitorar as duas branches principais do repositório

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Necessário para garantir que o histórico completo de tags seja baixado

    - name: Configurar usuário Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Verificar se o PR foi mesclado
      run: |
        if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
          echo "PR foi mesclado!"
        else
          echo "PR não foi mesclado. Abortando o processo."
          exit 1
        fi

    - name: Determinar a branch de destino e criar a tag
      run: |
        BRANCH_NAME=${{ github.event.pull_request.base.ref }}
        echo "Branch de destino: $BRANCH_NAME"

        if [[ "$BRANCH_NAME" == "main" ]]; then
          # Exemplo para versão do main: 1.35.0.1
          VERSION="1.35.0.1"
          TAG_NAME="v$VERSION"
        elif [[ "$BRANCH_NAME" == "develop" ]]; then
          # Exemplo para versão do develop: 1.36.0.1
          VERSION="1.36.0.1"
          TAG_NAME="v$VERSION"
        else
          echo "Branch não suportada para criação de tag. Abortando."
          exit 1
        fi

        echo "Tag gerada: $TAG_NAME"
        
        # Criar a tag no repositório local
        git tag -a "$TAG_NAME" -m "Release para $BRANCH_NAME"

    - name: Enviar a tag para o repositório
      run: |
        echo "Enviando a tag $TAG_NAME para o repositório"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/deyvidksc/winthor-smart-hub-layouts.git "$TAG_NAME"

    - name: Confirmar a tag criada
      run: |
        git fetch --tags  # Garantir que as tags remotas sejam recuperadas
        git tag -l  # Listar as tags para confirmar que a tag foi criada
