name: Criar Artefato com Nome da Branch
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - develop   # ou qualquer outra branch de interesse

jobs:
  cria-artefato:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar arquivo com o nome da branch
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"  # Nome da branch de origem do PR
          echo "$BRANCH_NAME" > branch-name.txt  # Criando o arquivo com o nome da branch
          echo "Nome da branch: $BRANCH_NAME"  # Exibindo no log para depuração

      - name: Fazer upload do artefato com o nome da branch
        uses: actions/upload-artifact@v3
        with:
          name: branch-name-artifact  # Nome do artefato
          path: branch-name.txt       # Caminho do arquivo criado (no diretório de trabalho atual)
