name: CI/CD - Registrar Arquivos Modificados

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use o token correto aqui
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Get list of modified files
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        id: get_modified_files
        run: |
          # Listando arquivos modificados na última commit
          modified_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Extraindo as pastas
          modified_folders=$(echo "$modified_files" | grep -o '^[^/]\+' | sort | uniq)
          
          # Deletar o arquivo 'modified_folders.txt' caso já exista
          rm -f modified_folders.txt
          
          # Criando o arquivo novamente com a lista de pastas
          echo "$modified_folders" > modified_folders.txt

      - name: Commit modified folders
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Verificar se o arquivo foi alterado
          if [ -f modified_folders.txt ]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add modified_folders.txt
            git commit -m "Atualizar lista de pastas modificadas"

            # Autenticação com o token GH_TOKEN
            git config --global credential.helper 'cache --timeout=3600'
            echo "https://${{ secrets.GH_TOKEN }}:@github.com" > ~/.git-credentials

            # Realizar o 'git pull' antes de fazer o 'git push' para garantir que as mudanças remotas sejam integradas
            git pull origin ${{ github.base_ref }} --rebase

            # Empurrar para a branch correta
            git push https://github.com/${{ github.repository }} HEAD:${{ github.base_ref }}
          fi

