name: "CI/CD - Atualizar Version.json"

on:
  workflow_run:
    workflows: ["CI/CD - Criar Tag de Release"]
    types:
       - completed
       - success

permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório

jobs:
  update-version-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Isso garante que você tenha o histórico completo para comparar as branches

      - name: Print local (trunk) branch
        run: |
          # Exibe a branch local (trunk)
          echo "Branch local (trunk): $(git rev-parse --abbrev-ref HEAD)"

      - name: Print remote branches (origin)
        run: |
          # Exibe todas as branches remotas (origin)
          echo "Branches remotas (origin):"
          git branch -v

      - name: Print remote (origin) branch for current branch
        run: |
          # Exibe a branch remota associada à branch local atual
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Branch remota (origin) associada à branch local ($CURRENT_BRANCH):"
          git rev-parse --abbrev-ref origin/$CURRENT_BRANCH
