name: "CI/CD - Atualizar Version.json"

on:
  workflow_run:
    workflows: ["CI/CD - Criar Tag de Release"]
    types:
       - completed
       - success

permissions:
  contents: write  # Permite ao GITHUB_TOKEN fazer push para o repositório

jobs:
  update-version-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Isso garante que você tenha o histórico completo para comparar as branches

      - name: Print remote branch for PR (from git remote show origin)
        run: |
          # Obtém o nome da branch de origem do PR (head_ref)
          PR_BRANCH="${{ github.head_ref }}"
          
          # Exibe as informações do repositório remoto
          echo "Informações sobre o repositório remoto (git remote show origin):"
          git remote show origin

          # Filtra o nome da branch de origem do PR
          echo "Branch de origem do PR (exemplo 'estudo_versoes')"
          git remote show origin | grep -oP '.*\s*pushes\s*to\s*\K\w+' | grep "$PR_BRANCH"
