name: "CI/CD - Atualizar Version.json"

on:
  workflow_run:
    workflows: ["CI/CD - Criar Tag de Release"]
    types:
       - completed
       - success

jobs:
  update-version-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Carregar a versão atual
        run: |
          # A versão será passada como variável de ambiente do workflow anterior
          echo "NEW_VERSION=${{ github.event.workflow_run.outputs.NEW_VERSION }}" >> $GITHUB_ENV

      - name: Buscar arquivos modificados
        id: modified_files
        run: |
          # Identifica os arquivos modificados na PR entre o último commit e a base da PR
          git diff --name-only ${{ github.event.workflow_run.head_sha }} ${{ github.sha }} > changed_files.txt
          cat changed_files.txt

      - name: Atualizar version.json nas pastas modificadas
        run: |
          # A versão obtida do workflow anterior será utilizada para atualizar o version.json
          NEW_VERSION="${{ env.NEW_VERSION }}"
          MODIFIED_FOLDERS=$(grep -oP '^[^/]+(?=/)' changed_files.txt | sort -u)

          for folder in $MODIFIED_FOLDERS; do
            # Ignorar as pastas não desejadas
            if [[ "$folder" == ".github" || "$folder" == "version-control" ]]; then
              continue
            fi

            # Verifica se existe um arquivo version.json dentro da pasta
            VERSION_JSON_PATH="$folder/version.json"
            if [[ -f "$VERSION_JSON_PATH" ]]; then
              echo "Atualizando $VERSION_JSON_PATH"
              # Atualiza a versão dentro do version.json
              jq ".versao = \"$NEW_VERSION\"" $VERSION_JSON_PATH > temp_version.json && mv temp_version.json $VERSION_JSON_PATH
              git add $VERSION_JSON_PATH
            fi
          done

      - name: Commit e Push das alterações no version.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Verifica se há alterações para commitar
          git diff --exit-code || git commit -m "Atualizando version.json para versão ${{ env.NEW_VERSION }}"
          
          # Push se houver alterações
          git push origin ${{ github.ref }} || echo "Nenhuma alteração para push"
