name: CI/CD - Atualização de Versão com Java

on:
  push:
    branches:
      - '**'  # Isso irá acionar o workflow para qualquer branch (ajustado para todas as branches)
    paths:
      - 'pfizer/**'
      - 'pdvsync/**'
      - '**/versao.json'  # Aciona para qualquer alteração no versao.json

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configuração do Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'  # Usando a distribuição correta (temurin)

    - name: Copiar o JAR do repositório
      run: |
        # Copia o JAR da pasta version-control-layouts para o diretório target (onde será executado)
        mkdir -p target  # Cria o diretório onde o JAR será colocado
        cp version-control/version-control-layouts.jar target/  # Copia o JAR para o diretório target

    - name: Executar o arquivo JAR para atualizar a versão
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}  # Obtém o nome do branch (exclui 'refs/heads/')
        echo "Nome do Branch: $BRANCH_NAME"  # Exibe o nome do branch
        java -jar target/version-control-layouts.jar $BRANCH_NAME  # Passa o nome do branch para o JAR
